### ISSUE TITLE
IATI Datastore CSV Query Builder does not work at all

### ISSUE THREAD

**Issue by jabbamon** [IATI/IATI-Query-Builder#104]
The previous version of the IATI Datastore CSV Query Builder worked beautifully. I am very frustrated to see that it has been replaced by a version which, while more visually appealing, does not work at all. Every query I make returns the error: "Internal Server Error. The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

I have even limited my search to results which I know are in the registry (because I downloaded them last summer). But alas, even a search that should produce even only a few results is too much for the Query Builder to handle now. For instance, this query should produce no more than 50 results: http://datastore.iatistandard.org/api/1/access/transaction.csv?reporting-org=DK-1&sector=13040&recipient-country=UG
but I just get an error.

**Comment by andylolz** [comment]
Ouch – yes, this looks very broken. Thanks for raising it, @jabbamon.

However, it’s unrelated to the upgrade to a new, more visually appealing query builder, but is instead an issue with the underlying datastore.

If you click any of the example links on the [‘forming queries’ documentation page](http://iatistandard.org/202/guidance/datastore/guidance/forming-queries/), you’ll see they all return an internal server error.

I’ve opened a new issue on the datastore repo: IATI/IATI-Datastore#289

And have tweeted [@IATI_aid](https://twitter.com/IATI_aid): https://twitter.com/andylolz/status/949609280772169728

**Comment by hayfield** [comment]
As noted by @andylolz, this is an issue with the Datastore rather than the Query Builder.

I will close this issue in favour of IATI/IATI-Datastore#289 so that there is just one open issue around this problem.
