### ISSUE TITLE
All 2016 GlobalGiving Data

### ISSUE THREAD

**Issue by supriyakkumar** [IATI/IATI-Query-Builder#106]
Hi,
I'm trying to download all 2016 giving data for GlobalGiving (US-EIN-300108263). I want to get all their giving for 2016 to all regions and countries, and not limited to specific sectors. When I try to generate this file, I keep getting a blank csv file. Can someone please help?
Thanks!

**Comment by hayfield** [comment]
Taking a look at the [GlobalGiving Activity Dataset](https://iatiregistry.org/dataset/globalgiving-activity) directly, it does not mention 2016 anywhere in it. As such, they do not appear to be publishing any data for their 2016 activities, so the returned CSV file will be empty.

**Comment by hayfield** [comment]
Since this issue appears to be with a publisher's Dataset rather than the Query Builder, I will close this Issue.

If you have any further queries, sending your query to the [Support email address](https://www.aidtransparency.net/contact/support) will reliably give you the best response.
