### ISSUE TITLE
Land Islands

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Query-Builder#11]
For some reason the ÅLAND ISLANDS are coming up as Land Island on the production server, but not on the dev

**Comment by dalepotter** [comment]
More robust approach for this issue added in d3d034c.

**Comment by hayfield** [comment]
@dalepotter With the fix you mentioned, can this issue be closed?

**Comment by andylolz** [comment]
Yep fix looks good, this looks closable to me.

**Comment by dalepotter** [comment]
Thanks @andylolz @hayfield 

Now closing this issue.
