### ISSUE TITLE
Data for Reporting Organisation dropdown

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Query-Builder#14]
This is currently being driven from the Registry.

a) Not all Publisher records contain iati-ids
b) Some publishers have recorded incorrect iati-ids

@bill-anderson is working of data improvements

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), this is deemed a legacy product.

The future of this tool or something with a similar feature set will be determined along with a review of the Datastore. Should a reworked version of the tool be developed, it will be based on the [IATI Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720).

The library should provide some manner of determining a list of all reporting organisations, however it needs to be determined what the best method to do this may be. As such, this issue has been labelled as an item for consideration.
