### ISSUE TITLE
Possible to build a query that fails due to its length

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Query-Builder#15]
[Extreme example](http://iati-datastore.herokuapp.com/api/1/access/activity.csv?reporting-org=GB-COH-294860%7CGB-CHC-1074937%7CGB-CHC-261488%7CGB-CHC-290836%7CNL-KVK-27264198%7CGB-CHC-274467%7CGB-CHC-105348%7Cgb-chc-1093624%7CGB-CHC-313139%7C46002%7CGB-CHC-1064413%7CGB-COH-1100897%7CGB-CHC-283302%7CNL-KVK-27327087%7CGB-CHC-327421%7C46004%7CNG-CAC-5938%7CAU-5%7CGB-CHC-1079599%7CGB-CC-1098893%7CGB-CHC-1068839%7CGB-CC-220949%7CGB-CHC-298316%7CGB-CHC-292506%7CUS-IRS-562339052%7CGB-2%7CGB-CHC-1029161%7CGB-CHC-1102028%7CGB-CC-285776%7CGB-CHC-CF%7Cciks%7CGB-CC-326568%7CGB-CHC-328434%7CGB-CHC-1020488%7CGB-CHC-110585%7CGB-CHC-272465%7CGB-CHC-1092236%7CGB-CHC-1055436%7CGB-CHC-1070684%7CDK-1%7CGB-1%7CIE-1%7CZA-ROC-1999%2F05072%2F08%7CGPAF-IMP-031%7CGB-COH-06368740%7CGB-CHC-1122924%7Cgb-coh-07629751%7CCA-CRA-89980-1815-RR0001%7CGB-COH-3578127%7CEU-5%7CEU-6%7CEU%7CGB-CC-1089879%7CGB-COH-01926828%7CGB-COH-0277068%7CFI-3%7CCA-3%7CGB-COH-3008440%7CNP-DAO-27-127%2F062%2F063%7CGB-CHC-281681%7C47122%7CCHY6271%7CZA-CIPC-2001%2F005850%2F08%7CDE-1%7CUS-EIN-26-0126537%7CUS-EIN-300108263%7CGB-CHC-1043641%7CFR-PDR-W691075333%7CGB-CHC-1837621%7CGB-COH-4887855%7CHEIFER%7CGB-COH-1762840%7CNL-KVK-41198677%7CGB-CHC-1017255%7CGB-CHC-1089490%7CGB-CHC-1090745%7CGB-CHC-1075920%7CIADB%7CICN%7CGB-CHC-1001698%7CGB-COH-21531930%7C21020%7CGB-CHC-21023%7CGB-CHC-328158%7CGB-CHC-291167%7Ckaruna_admin%7CGB-COH-4075590%7CGB-CHC-218186%7CGB-SC-037959%7CGB-CHC-800672%7CIN-%7CGB-CHC-1099776%7CIM-CR-017899B%7Cmapaction%7CGB-COH-1102208%7CSL-NRA-1001562-8%7CGB-CHC-SC030289%7CGB-CHC-291691%7CGB%2FCHC%2F1104287%7CES-5%7CNL-1%7CGB-CHC-1079358%7CNP-DAO-27-689%2F063%2F064%7CGB-CHC-1120932%7CNO-BRC-977538319%7C41127-FTS%7CGB-COH-05322719%7CGB-CHC-202918%7CGB-CHC-1125948%7CUS-EIN-13-2702768%7CGB-CHC-1123241%7CGB-COH-04154075%7CGB-CHC-1078768%7CGB-COH-1364201%7Cpontis%7C21032%7CGB-CHC-1059996%7CGB-COH-871954%7CIN-AR-775%7CGB-CHC-294329%7CGB-COH-07676886%7CGB-CHC-207076%7CGB-CHC-1058991%7CGB-CHC-1138287%7CGB-CHC-1098106%7CGB-COH-4905100%7CGB-CHC-1127488%7CGB-COH-2100867%7CNL-KVK-41213450%7CGB-CHC-3015948%7CGB-CHC-1001349%7CGB-COH-213890%7CSCIAF%7CIE-6663%7CGB-CHC-299717%7CSACU%7CGB-CHC-1076497%7CGB-CHC-207544%7CZA-NPO-061870%7CGB-CHC-1065705%7CSE-6%7CGB-CHC-1071886%7CGB+CHC+265464%7CUS-AGO-CA-941191246%7CGB-CHC-327654%7C30001%7C47045%7CGB-CC-254781%7CGB-CHC-1050327%7CUS-EIN-941655673%7C44000%7CGB-COH-3031674%7C21033%7CGB-COH-NI21482%7CGB-CHC-1069208%7CGB-CHC-291824%7CGB-9%7CGB-4%7CGB-3%7CGB-GOVUK-uk_Home+Office%7C411124%7C41120%7C41AAA%7C41111%7C41122%7C41114%7C41119%7C41140%7CUS%7C302%7CGB-CHC-1140123%7CGB-CHC-313757%7CGB-COH-1081247%7CGB-CHC-208724%7CGB-COH-5419428%7CGB-CC-288701%7CGBCHC328206%7CGB-CHC-1115109%7CGB-COH-2082273%7CGB-CHC-285908%7C21-PK-WWF%7CGB-CHC-1109789%7CNP-CRO-45995%2F063%2F064&reporting-org.type=10%7C15%7C21%7C22%7C23%7C30%7C40%7C60%7C70%7C80&sector=11110%7C11120%7C11130%7C11182%7C11220%7C11230%7C11240%7C11320%7C11330%7C11420%7C11430%7C12110%7C12181%7C12182%7C12191%7C12220%7C12230%7C12240%7C12250%7C12261%7C12262%7C12263%7C12281%7C13010%7C13020%7C13030%7C13040%7C13081%7C14010%7C14015%7C14020%7C14030%7C14040%7C14050%7C14081%7C15110%7C15120%7C15130%7C15140%7C15150%7C15161%7C15162%7C15163%7C15164%7C15210%7C15220%7C15230%7C15240%7C15250%7C15261%7C16010%7C16020%7C16030%7C16040%7C16050%7C16061%7C16062%7C16063%7C16064%7C21010%7C21020%7C21030%7C21040%7C21050%7C21061%7C21081%7C22010%7C22020%7C22030%7C22040%7C23010%7C23020%7C23030%7C23040%7C23050%7C23061%7C23062%7C23063%7C23064%7C23065%7C23066%7C23067%7C23068%7C23069%7C23070%7C23081%7C23082%7C24010%7C24020%7C24030%7C24040%7C24081%7C25010%7C25020%7C31110%7C31120%7C31130%7C31140%7C31150%7C31161%7C31162%7C31163%7C31164%7C31165%7C31166%7C31181%7C31182%7C31191%7C31192%7C31193%7C31194%7C31195%7C31210%7C31220%7C31261%7C31281%7C31282%7C31291%7C31310%7C31320%7C31381%7C31382%7C31391%7C32110%7C32120%7C32130%7C32140%7C32161%7C32162%7C32163%7C32164%7C32165%7C32166%7C32167%7C32168%7C32169%7C32170%7C32171%7C32172%7C32182%7C32210%7C32220%7C32261%7C32262%7C32263%7C32264%7C32265%7C32266%7C32267%7C32268%7C32310%7C33110%7C33120%7C33130%7C33140%7C33150%7C33181%7C33210%7C41010%7C41020%7C41030%7C41040%7C41050%7C41081%7C41082%7C43010%7C43030%7C43040%7C43050%7C43081%7C43082%7C51010%7C52010%7C53030%7C53040%7C60010%7C60020%7C60030%7C60040%7C60061%7C60062%7C60063%7C72010%7C72040%7C72050%7C73010%7C74010%7C91010%7C92010%7C92020%7C92030%7C93010%7C99810%7C99820)

**Comment by hayfield** [comment]
Browsers have a maximum length that URLs may be. As such, use of POST data rather than Query Strings to provide input to a Datastore may be beneficial.

**Comment by hayfield** [comment]
Have created an issue against the Datastore at IATI/IATI-Datastore#248 to log against the root problem.

**Comment by hayfield** [comment]
Am labelling as a `consideration` since it needs to be kept in mind for any future development on this or similar tools.

**Comment by andylolz** [comment]
Funnily enough @Bjwebb’s URL (which points at http://iati-datastore.herokuapp.com) does work as a POST request, but 405s on the live datastore. So presumably POST requests were at some point accepted by the datastore API.
