### ISSUE TITLE
Enable new filter options on the form

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Query-Builder#18]
New filters are being added to the datastore API.

We need to review them, and add them to the form if appropriate.
See https://github.com/okfn/iati-datastore/issues/120

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), this is deemed a legacy product.

The future of this tool or something with a similar feature set will be determined along with a review of the Datastore. Should a reworked version of the tool be developed, it will be designed to fully integrate with the Datastore and as such it should not be necessary to manually add new filters in this sort of manner.
