### ISSUE TITLE
Organisation Type drop down

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Query-Builder#2]
Could build this drop down from the codelist API

This is built from a static csv obtained from the API. What I mean is that we could find a way to update it automagically if the codelist changes

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), this is deemed a legacy product.

The future of this tool or something with a similar feature set will be determined along with a review of the Datastore. Should a reworked version of the tool be developed, it will be based on the [IATI Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720) and bring in Codelist values in that manner.
