### ISSUE TITLE
Country drop down

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Query-Builder#3]
Could build this from the codelist API

Currently it is built form a CSV downloaded from the codelist API - we just to need to maybe automate it to pull a new codelist version when there is one.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), this is deemed a legacy product.

The future of this tool or something with a similar feature set will be determined along with a review of the Datastore. Should a reworked version of the tool be developed, it will be based on the [IATI Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720) and bring in Codelist values in that manner.
