### ISSUE TITLE
Reporting org example uses code from old organisation identifier codelist

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Query-Builder#30]
I think DFID is now referenced by GB-GOV-1, not GB-1.

![screen shot 2017-03-10 at 15 22 51](https://cloud.githubusercontent.com/assets/464193/23829825/a123932e-06f3-11e7-9c67-e5e6f8bf51d6.png)

**Comment by dalepotter** [comment]
Closing as this is now integrated into the code and deployed to the live instance.

**Comment by andylolz** [comment]
🚀 🚀 🚀
