### ISSUE TITLE
Reporting orgs not in alphabetical order

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Query-Builder#33]
The 'Select Reporting Organisation' multiselect field on the [Query builder](http://datastore.iatistandard.org/query/) does not show organisations in alphabetical order.

For example: 
![image](https://cloud.githubusercontent.com/assets/8247168/24505663/a098f0a8-1552-11e7-8671-8c795a983644.png)

This looks to be a good place to start for the root cause: https://github.com/IATI/IATI-Query-Builder/blob/master/helpers/functions.php#L62

**Comment by YohannaLoucheur** [comment]
Any hope of progress on this?  I'm anxious, as one of the users of the Query Builder whose reporting org is misplaced (and who needs to apologize to colleagues for it whenever I give instructions on how to use the QB).

**Comment by andylolz** [comment]
@YohannaLoucheur does this help? http://please.treadsoft.ly/query/

If so, I’ll send a pull request with the typeaheads.

If not, sorting should be super straightforward.

**Comment by YohannaLoucheur** [comment]
Yes, that's great, thanks Andy!

**Comment by andylolz** [comment]
Re. sorting… I think this was broken in ecb625bd. `SORT_NATURAL` and `SORT_FLAG_CASE` [were introduced in PHP 5.4](http://php.net/manual/en/function.sort.php), but the query builder server is running PHP 5.3.10. Two solutions:

 * upgrade to PHP 5.4
 * use [this backwards compatible solution](https://stackoverflow.com/questions/12180324/array-case-insensitive-key-sort-in-php-version-5-3-or-less#12180325)

I’ve sent a PR for the latter.

**Comment by dalepotter** [comment]
Closing this issue as this has now been deployed to both the [dev](http://dev.datastore.iatistandard.org/query/) and [live](http://datastore.iatistandard.org/query/) query builders.
