### ISSUE TITLE
Move licence information from readme to separate files

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Query-Builder#35]
The licences need some housekeeping to keep the readme file nice and clean.

Lines affected: https://github.com/IATI/IATI-Query-Builder/blame/master/README.md#L59-L90

- [ ] Move IATI-Query-Builder licence to `LICENCE.txt`
- [ ] Move 'Ckan_client-PHP' & 'PHP Markdown' licences to `LICENSES-3RD-PARTY.txt`

**Comment by andylolz** [comment]
Looks like it was fixed in 6909052a 🚀

**Comment by dalepotter** [comment]
:-) Indeed, this is fixed!
