### ISSUE TITLE
Erroneous label in csv download 

### ISSUE THREAD

**Issue by YohannaLoucheur** [IATI/IATI-Query-Builder#42]
When building a query based on transactions (ie selecting "one transaction per row" as format), the resulting csv data contains a field/column labeled: transaction_provider-org_provider-activity-id  

Yet this field contains the provider-id, not provider-activity-id  (and only for some transactions). 

Sorry, I tried to add a screen capture but seem unable to paste anything here.

**Comment by andylolz** [comment]
You should be able to drag and drop your screenshot into the comment box.

In fact, a screenshot would be great, as I just tested and I don’t see this bug.

**Comment by YohannaLoucheur** [comment]
Does this work? I wasn't able to paste in IE, but I was in Chrome. Otherwise I'll email it.

![image](https://user-images.githubusercontent.com/6749013/28574275-7486a832-711b-11e7-8f75-8325290ccc25.png)

**Comment by YohannaLoucheur** [comment]
Just realized that this shot only has empty cells, as it's a very small subset of the file.  Here's another shot.

![image](https://user-images.githubusercontent.com/6749013/28574450-09821cdc-711c-11e7-8034-cdebe1433246.png)

**Comment by andylolz** [comment]
Here’s the XML for the first activity in your screenshot, via d-portal:
http://d-portal.org/q.xml?aid=CA-3-A034216001

The only transaction says:
```xml
<transaction>
    <transaction-type code="2"/>
    <transaction-date iso-date="2011-08-03"/>
    <value value-date="2011-08-03">10250000.00</value>
    <provider-org provider-activity-id="CA-3"/>
    <flow-type code="10"/>
    <tied-status code="5"/>
</transaction>
```

So I think this is a data bug rather than a datastore bug.

**Comment by YohannaLoucheur** [comment]
Duh...  Should have checked that, sorry and thanks

**Comment by hayfield** [comment]
Since this appears to be a data bug rather than a datastore bug, I will close this issue.
