### ISSUE TITLE
Open github in new tab from Query-Builder

### ISSUE THREAD

**Issue by YohannaLoucheur** [IATI/IATI-Query-Builder#43]
When clicking on Github or "report an issue" at bottom of the Query Builder, it would be better to have it open as a new tab rather than leaving the QB, as we often need to check back on QB to provide details on the issue.

**Comment by andylolz** [comment]
I don’t know if this helps… But you can right-click and “open in new tab” on most browsers. The power is in your hands! 🙌

**Comment by YohannaLoucheur** [comment]
I know I can do it myself, but as a user I assume the design is built around my needs. A "report an issue" button is (almost) never the reason I went to a website, so it's quite unlikely I want to leave it to go to github. 
Also, you assume the user is using a mouse, which isn't necessarily the case.

**Comment by andylolz** [comment]
> Also, you assume the user is using a mouse

I most certainly do not! I never use a mouse, nor do I work on a device with right-click! But there’s usually a right-click equivalent (mine is set up to two-finger tap the touchpad). But I digress.

Re. bad practice: So “open in new tab” is done with `target="_blank"`. Here’s what hacker news says about that:
https://hn.algolia.com/?query=target%20blank&sort=byPopularity&prefix&page=0&dateRange=all&type=story

**Comment by hayfield** [comment]
It's not an entirely clear-cut topic, and there are a range of factors at play (internal vs. external link, user flow, trust of external link, etc).

I've added it to our list of 'small modifications to discuss implementing'.

**Comment by andylolz** [comment]
> (internal vs. external link, user flow, trust of external link, etc).

Accessibility? Here’s the gov.uk guidance recommending against it on those grounds:
https://paper.dropbox.com/doc/Links-xiWNcJk5Wpb8Sj6G4Prtl

**Comment by hayfield** [comment]
From that doc:

> If opening a link in the same tab would result in a user losing their progress in a transaction, then it's preferable to open the link in a new tab. Let users know that the link will open in a new tab.

This is the case with the Query Builder, so it should be a new tab.

**Comment by andylolz** [comment]
> would result in a user losing their progress in a transaction

Because the query builder is a form? I suppose you could interpret the advice like that, sure!

**Comment by YohannaLoucheur** [comment]
FWIW, on Discuss if I click on a link in a post, a new tab opens.

**Comment by andylolz** [comment]
> FWIW, on Discuss if I click on a link in a post, a new tab opens.

We figured this out (on twitter). Discourse actually has a user preference for this. So the user is still in control.

**Comment by allthatilk** [comment]
This change has now been deployed to live.
